name: CMake on a single platform
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
env:
    BUILD_TYPE: Debug
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Structure
      run: |
        ls
        cd GrblParser
        ls
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
